projectoption:
    pattern:  /
    defaults: { _controller: "DafuerGetOptGeneratorBundle:ProjectOption:index" }

projectoption_show:
    pattern:  /{id}/show
    defaults: { _controller: "DafuerGetOptGeneratorBundle:ProjectOption:show" }

projectoption_new:
    pattern:  /new
    defaults: { _controller: "DafuerGetOptGeneratorBundle:ProjectOption:new" }

projectoption_create:
    pattern:  /create
    defaults: { _controller: "DafuerGetOptGeneratorBundle:ProjectOption:create" }
    requirements: { _method: post }

projectoption_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DafuerGetOptGeneratorBundle:ProjectOption:edit" }

projectoption_update:
    pattern:  /{id}/update
    defaults: { _controller: "DafuerGetOptGeneratorBundle:ProjectOption:update" }
    requirements: { _method: post }

projectoption_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DafuerGetOptGeneratorBundle:ProjectOption:delete" }
    requirements: { _method: post }
