DafuerGetOptGeneratorBundle_project:
    pattern:  /
    defaults: { _controller: "DafuerGetOptGeneratorBundle:Project:index" }

DafuerGetOptGeneratorBundle_project_show:
    pattern:  /{id}/show
    defaults: { _controller: "DafuerGetOptGeneratorBundle:Project:show" }

DafuerGetOptGeneratorBundle_project_new:
    pattern:  /new
    defaults: { _controller: "DafuerGetOptGeneratorBundle:Project:new" }

DafuerGetOptGeneratorBundle_project_create:
    pattern:  /create
    defaults: { _controller: "DafuerGetOptGeneratorBundle:Project:create" }
    requirements: { _method: post }
    
DafuerGetOptGeneratorBundle_project_edit2:
    pattern:  /{id}/edit2
    defaults: { _controller: "DafuerGetOptGeneratorBundle:Project:edit2" }  
    
DafuerGetOptGeneratorBundle_project_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DafuerGetOptGeneratorBundle:Project:edit" }
  

DafuerGetOptGeneratorBundle_project_update:
    pattern:  /{id}/update
    defaults: { _controller: "DafuerGetOptGeneratorBundle:Project:update" }
    requirements: { _method: post }

DafuerGetOptGeneratorBundle_project_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DafuerGetOptGeneratorBundle:Project:delete" }
    requirements: { _method: post }
