parameters:
#    dafuer_get_opt_generator.example.class: Dafuer\GetOptGeneratorBundle\Example

services:
#    dafuer_get_opt_generator.example:
#        class: %dafuer_get_opt_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
